### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/skill-words#1]
I just want to say this is freaking awesome!

Let me know if you want to transfer it to an official skill.

Also you might want a `requirements.txt` file in order for others to be able to install it.

**Comment by FabioRosado** [comment]
Thanks Jacob glad you like it! 👍  I'll transfer it to you it would be awesome to make it an official skill.
I still need to work on the dictionary because at the moment it only returns nouns haha

**Comment by jacobtomlinson** [comment]
Great!
